# Generated by Django 4.1.5 on 2023-02-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
