# Generated by Django 4.1.5 on 2023-02-03 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_alter_snippet_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippet',
            options={},
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='highlighted',
        ),
    ]
